/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateQuizRouteImport } from './routes/create-quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsQuizIdRouteImport } from './routes/results.$quizId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateQuizRoute = CreateQuizRouteImport.update({
  id: '/create-quiz',
  path: '/create-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsQuizIdRoute = ResultsQuizIdRouteImport.update({
  id: '/results/$quizId',
  path: '/results/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-quiz': typeof CreateQuizRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results/$quizId': typeof ResultsQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-quiz': typeof CreateQuizRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results/$quizId': typeof ResultsQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-quiz': typeof CreateQuizRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results/$quizId': typeof ResultsQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-quiz' | '/dashboard' | '/login' | '/results/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-quiz' | '/dashboard' | '/login' | '/results/$quizId'
  id:
    | '__root__'
    | '/'
    | '/create-quiz'
    | '/dashboard'
    | '/login'
    | '/results/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateQuizRoute: typeof CreateQuizRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResultsQuizIdRoute: typeof ResultsQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-quiz': {
      id: '/create-quiz'
      path: '/create-quiz'
      fullPath: '/create-quiz'
      preLoaderRoute: typeof CreateQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$quizId': {
      id: '/results/$quizId'
      path: '/results/$quizId'
      fullPath: '/results/$quizId'
      preLoaderRoute: typeof ResultsQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateQuizRoute: CreateQuizRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResultsQuizIdRoute: ResultsQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
